# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56f1ddad47f6a85ef0f8acfb80de327b67454f981089bc2366a4bd38df1b0e4da8047b89652b9d65ebb6fb880000c99797bb14fa45cf361d84b9ada6837ef054

test:
  secret_key_base: aa70f0cb6d452f220a8f2c635be5e96d582699630af248418444e0a6db412aeb8f6175985be4a52446b8b1a69940acd8892f77e240b4d29137668fc9a2f701dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
